# Generated by Django 4.1.5 on 2024-01-07 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serverv', '0002_sensor_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
