# Generated by Django 4.1.5 on 2024-01-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverv', '0003_alter_sensor_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_data',
            name='height',
            field=models.CharField(default=140, max_length=140),
            preserve_default=False,
        ),
    ]
