# Generated by Django 4.1.5 on 2024-01-28 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverv', '0004_sensor_data_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_data',
            name='height',
            field=models.IntegerField(),
        ),
    ]
