# Generated by Django 4.1.5 on 2024-01-28 10:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serverv', '0005_alter_sensor_data_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor_data',
            name='height',
        ),
        migrations.CreateModel(
            name='tank_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='serverv.sensor_data')),
            ],
        ),
    ]
