# Generated by Django 4.1.5 on 2024-01-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serverv', '0006_remove_sensor_data_height_tank_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor_data',
            name='height',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='tank_data',
        ),
    ]
