# Generated by Django 4.1.5 on 2024-01-28 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serverv', '0007_sensor_data_height_delete_tank_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor_data',
            name='height',
        ),
    ]
